### PR TITLE
add a test for api key on calls to regulations.gov

### PR DESCRIPTION
**Pull request by bjcoleman**

### CODE REVIEW

**Comment by bjcoleman** [comment]
I merged in the PR with the `_` vs. `-` fix and verified that it runs successfully on my machine.  @esvicente @mmorykan @mattkosack @CoryLittle02 can you verify that it works for you on your laptop?

**Comment by mattkosack** [comment]
This worked on my laptop. 👍

**Comment by mmorykan** [comment]
Works for me too.

**Comment by bjcoleman** [comment]
Ok, let's get this merged then.

**Pull request merged**
