### PR TITLE
implemented backend logic for redis db lookups of queued jobs

### PR DESCRIPTION
**Pull request by gorskie**
Ready for review

### CODE REVIEW

**Comment by gorskie** [comment]
This is ready for review

**Comment by marchesem764** [comment]
There is a lot to review here may take a decent bit of time to encapsulate all of the details. I'll need sometime to review this

**Comment by marchesem764** [comment]
In the future it may be beneficial to block together working commits into smaller PRs. We primarily highlighted this theme during our sprint 3 readout and it'll be good to revoke the idea more frequently for all of us.

**Comment by ShaneHoughton** [comment]
I just think the only thing that needs to be considered is readability in dashboad_server.py when you return all those values. I see that it's being returned as a dictionary, so I think that the values should be variables like how you have "'clients_total' : clients_total" instead of "'num_jobs_waiting: int(redis_db.llen(...))"

**Pull request merged**
