### PR TITLE
catch Nonetype Error in Client

### PR DESCRIPTION
**Pull request by Glennonr**

### CODE REVIEW

**Comment by bjcoleman** [comment]
Do we have a sense of *why* this error is occurring?

**Comment by Glennonr** [comment]
> Do we have a sense of _why_ this error is occurring?

some json that should be the list of attachments from regulations look like this instead of the regular format:
{"data" : [ ]} that could be a potential cause

**Comment by bjcoleman** [comment]
Ok, what will the client do when this happens?  Right now, it appears that jobs are being assigned but never accounted for because the client crashes.  I think it should return the error state (like we do on a 400 return value)

**Comment by pereze03** [comment]
Based on previous comments this pull request seems to be unfinished. It should not be merged, however, if the error continues to occur once the system is running then it should be referred back to.

**Pull request closed without merging**
